export type DocLink = { slug: string; title: string; description: string; href: string; };
export type NavNode =
  | { kind: "label"; title: string }
  | { kind: "link"; slug: string; title: string; href: string }
  | { kind: "folder"; title: string; children: DocLink[] };

export const PAGES: DocLink[] = [
  { slug: "quick-guide", title: "快速手册", description: "日常最高频：建账号、拿密钥、起沙箱、跑代码。", href: "/docs/quick-guide" },
  { slug: "updates", title: "同步日志", description: "官网每次变动后，这里单独记一笔：改了什么、中文站在哪一页。", href: "/docs/updates" },
  { slug: "architecture-site", title: "本站架构", description: "手册怎么拼起来，以及每日同步如何驱动汉化。", href: "/docs/architecture-site" },
  { slug: "sitemap", title: "对照表", description: "官网每一页的指纹；哈希一变就能定位中文站要改哪一页。", href: "/docs/sitemap" },
  { slug: "index", title: "Daytona 是什么", description: "安全弹性的 AI 代码沙箱：完整可组合计算机。", href: "/" },
  { slug: "sandboxes", title: "沙箱", description: "隔离运行时：容器、Linux VM、Windows、macOS、GPU。", href: "/docs/sandboxes" },
  { slug: "snapshots", title: "快照", description: "沙箱状态的持久捕获，用来快速创建新沙箱。", href: "/docs/snapshots" },
  { slug: "volumes", title: "卷", description: "跨沙箱共享的持久文件访问。", href: "/docs/volumes" },
  { slug: "regions", title: "区域", description: "沙箱运行的地理或逻辑位置。", href: "/docs/regions" },
  { slug: "architecture", title: "架构", description: "接口平面、控制平面、计算平面。", href: "/docs/architecture" },
  { slug: "isolation", title: "隔离", description: "运行时、网络与组织隔离。", href: "/docs/isolation" },
  { slug: "persistence", title: "持久化", description: "文件系统、内存、快照、卷与生命周期。", href: "/docs/persistence" },
  { slug: "scale", title: "扩展", description: "沙箱扩展、机群扩展与工作负载并发。", href: "/docs/scale" },
  { slug: "api-keys", title: "认证", description: "API 密钥、JWT、权限范围与托管密钥。", href: "/docs/api-keys" },
  { slug: "organizations", title: "组织", description: "成员、用量、配额与沙箱类型。", href: "/docs/organizations" },
  { slug: "billing", title: "计费", description: "钱包、用量、发票与取消结算。", href: "/docs/billing" },
  { slug: "limits", title: "限额", description: "资源、沙箱数量与磁盘配额。", href: "/docs/limits" },
  { slug: "troubleshooting", title: "故障排查", description: "生命周期、账号、运行时与错误处理。", href: "/docs/troubleshooting" },
  { slug: "playground", title: "Playground", description: "浏览器里创建沙箱、跑 SDK、开终端和 VNC。", href: "/docs/playground" },
  { slug: "file-system-operations", title: "文件系统操作", description: "列目录、上传下载、权限与搜索。", href: "/docs/file-system-operations" },
  { slug: "git-operations", title: "Git 操作", description: "克隆、分支、提交与远程。", href: "/docs/git-operations" },
  { slug: "process-code-execution", title: "进程与代码执行", description: "跑代码、会话、后台命令与超时。", href: "/docs/process-code-execution" },
  { slug: "pty", title: "PTY", description: "交互式伪终端会话。", href: "/docs/pty" },
  { slug: "language-server-protocol", title: "语言服务器协议", description: "在沙箱里开 LSP、补全与符号。", href: "/docs/language-server-protocol" },
  { slug: "computer-use", title: "计算机使用", description: "鼠标、键盘、截图与桌面自动化。", href: "/docs/computer-use" },
  { slug: "declarative-builder", title: "声明式构建", description: "用代码声明镜像并构建快照。", href: "/docs/declarative-builder" },
  { slug: "log-streaming", title: "日志流", description: "实时拉取进程与会话日志。", href: "/docs/log-streaming" },
  { slug: "preview", title: "预览", description: "把沙箱端口暴露成预览 URL。", href: "/docs/preview" },
  { slug: "custom-preview-proxy", title: "自定义预览代理", description: "自建代理、WebSocket 与保留端口。", href: "/docs/custom-preview-proxy" },
  { slug: "web-terminal", title: "Web 终端", description: "仪表盘或 CLI 进入沙箱终端。", href: "/docs/web-terminal" },
  { slug: "vnc-access", title: "VNC 访问", description: "图形桌面与 Computer Use。", href: "/docs/vnc-access" },
  { slug: "ssh-access", title: "SSH 访问", description: "仪表盘、CLI、令牌与 IDE。", href: "/docs/ssh-access" },
  { slug: "mcp", title: "MCP 服务器", description: "让 Claude / Cursor / Windsurf 操作 Daytona。", href: "/docs/mcp" },
  { slug: "agent-skills", title: "Agent Skills", description: "给智能体安装 Daytona 技能。", href: "/docs/agent-skills" },
  { slug: "warm-pools", title: "温池", description: "预热沙箱池，降低冷启动。", href: "/docs/warm-pools" },
  { slug: "mount-external-storage", title: "挂载外部存储", description: "把对象存储挂进沙箱。", href: "/docs/mount-external-storage" },
  { slug: "secrets", title: "密钥", description: "注入、替换范围、脱敏与权限。", href: "/docs/secrets" },
  { slug: "sso", title: "组织 SSO", description: "OIDC、SCIM 与主流身份提供商。", href: "/docs/sso" },
  { slug: "linked-accounts", title: "关联账号", description: "把外部账号连到 Daytona。", href: "/docs/linked-accounts" },
  { slug: "audit-logs", title: "审计日志", description: "组织操作的实时审计。", href: "/docs/audit-logs" },
  { slug: "webhooks", title: "Webhooks", description: "沙箱、快照、卷事件回调。", href: "/docs/webhooks" },
  { slug: "observability/otel-collection", title: "OpenTelemetry 采集", description: "组织指标与用量遥测。", href: "/docs/observability/otel-collection" },
  { slug: "network-limits", title: "网络限额", description: "出站域名、CIDR 与预览鉴权。", href: "/docs/network-limits" },
  { slug: "vpn-connections", title: "VPN 连接", description: "Tailscale、OpenVPN、Netbird。", href: "/docs/vpn-connections" },
  { slug: "bring-your-own-compute", title: "自带算力", description: "自定义区域与 Helm 部署。", href: "/docs/bring-your-own-compute" },
  { slug: "tools/cli", title: "CLI", description: "安装与全部 daytona 命令。", href: "/docs/tools/cli" },
  { slug: "tools/api", title: "API 参考", description: "Platform、Toolbox、Analytics。", href: "/docs/tools/api" },
  { slug: "typescript-sdk", title: "TypeScript SDK", description: "@daytona/sdk 安装、配置与实时状态。", href: "/docs/typescript-sdk" },
  { slug: "python-sdk", title: "Python SDK", description: "pip install daytona，同步与异步客户端。", href: "/docs/python-sdk" },
  { slug: "go-sdk", title: "Go SDK", description: "sdk-go 安装与入门。", href: "/docs/go-sdk" },
  { slug: "java-sdk", title: "Java SDK", description: "Maven / Gradle 与入门。", href: "/docs/java-sdk" },
  { slug: "ruby-sdk", title: "Ruby SDK", description: "gem install daytona。", href: "/docs/ruby-sdk" },
  { slug: "guides", title: "指南总览", description: "Daytona 与各类智能体、框架、GPU 服务的集成指南。", href: "/docs/guides" },
  { slug: "guides/claude", title: "Claude 指南", description: "在沙箱里跑 Claude Code、Agent SDK 与托管智能体。", href: "/docs/guides/claude" },
  { slug: "guides/openai", title: "OpenAI 指南", description: "Agents SDK、Codex、自托管沙箱与 Text-to-SQL。", href: "/docs/guides/openai" },
  { slug: "guides/cursor", title: "Cursor 指南", description: "在 Daytona 上跑 Cursor Self-Hosted Machines。", href: "/docs/guides/cursor" },
  { slug: "guides/devin", title: "Devin 指南", description: "Devin CLI 与 Outposts。", href: "/docs/guides/devin" },
  { slug: "guides/opencode", title: "OpenCode 指南", description: "插件、SDK Agent 与 Web Agent。", href: "/docs/guides/opencode" },
  { slug: "guides/openclaw", title: "OpenClaw 指南", description: "安全沙箱与 SDK。", href: "/docs/guides/openclaw" },
  { slug: "guides/rlm", title: "RLM 指南", description: "递归语言模型相关集成。", href: "/docs/guides/rlm" },
  { slug: "guides/ag2/ag2-bug-fixer-agent", title: "AG2 缺陷修复智能体", description: "用 AG2 在 Daytona 沙箱里修 bug。", href: "/docs/guides/ag2/ag2-bug-fixer-agent" },
  { slug: "guides/agentkit/inngest-agentkit-coding-agent", title: "Inngest AgentKit 编程智能体", description: "AgentKit + Daytona 编码工作流。", href: "/docs/guides/agentkit/inngest-agentkit-coding-agent" },
  { slug: "guides/amp/amp-sdk-coding-agent", title: "Amp SDK 编程智能体", description: "Amp SDK 跑在 Daytona 沙箱。", href: "/docs/guides/amp/amp-sdk-coding-agent" },
  { slug: "guides/brainbase/universal-harness-api", title: "Brainbase Universal Harness API", description: "把 Brainbase harness 接到沙箱。", href: "/docs/guides/brainbase/universal-harness-api" },
  { slug: "guides/claude/claude-agent-sdk-connect-service-sandbox", title: "Claude Agent SDK 连接服务", description: "在沙箱里连接外部服务。", href: "/docs/guides/claude/claude-agent-sdk-connect-service-sandbox" },
  { slug: "guides/claude/claude-agent-sdk-interactive-terminal-sandbox", title: "Claude Agent SDK 交互终端", description: "交互式终端沙箱。", href: "/docs/guides/claude/claude-agent-sdk-interactive-terminal-sandbox" },
  { slug: "guides/claude/claude-code-run-cli-sandbox", title: "用 CLI 在沙箱跑 Claude Code", description: "安装 CLI、创建沙箱、SSH 后启动 claude。", href: "/docs/guides/claude/claude-code-run-cli-sandbox" },
  { slug: "guides/claude/claude-code-run-tasks-stream-logs-sandbox", title: "Claude Code 跑任务并流式日志", description: "非交互任务与日志流。", href: "/docs/guides/claude/claude-code-run-tasks-stream-logs-sandbox" },
  { slug: "guides/claude/claude-managed-agents", title: "Claude 托管智能体", description: "托管 Claude 智能体跑在 Daytona。", href: "/docs/guides/claude/claude-managed-agents" },
  { slug: "guides/claude/data-analysis-with-ai", title: "用 AI 做数据分析", description: "Claude + 沙箱做数据分析。", href: "/docs/guides/claude/data-analysis-with-ai" },
  { slug: "guides/copilotkit/copilotkit-generative-ui-coding-agent-sandbox", title: "CopilotKit 生成式 UI 编程智能体", description: "CopilotKit 编码智能体沙箱。", href: "/docs/guides/copilotkit/copilotkit-generative-ui-coding-agent-sandbox" },
  { slug: "guides/cursor/cursor-self-hosted-machines", title: "Cursor 自托管机器", description: "Self-Hosted Pool worker 跑在 Daytona 沙箱。", href: "/docs/guides/cursor/cursor-self-hosted-machines" },
  { slug: "guides/devin/devin-cli-run-tasks-stream-logs-sandbox", title: "Devin CLI 跑任务并流式日志", description: "Devin CLI + Daytona。", href: "/docs/guides/devin/devin-cli-run-tasks-stream-logs-sandbox" },
  { slug: "guides/devin/devin-outposts", title: "Devin Outposts", description: "把 Devin Outposts 接到 Daytona。", href: "/docs/guides/devin/devin-outposts" },
  { slug: "guides/flue/flue-autonomous-bug-fix-agent", title: "Flue 自主修 bug 智能体", description: "Flue 在沙箱里自动修缺陷。", href: "/docs/guides/flue/flue-autonomous-bug-fix-agent" },
  { slug: "guides/gemini/gemini-cli-run-tasks-stream-logs-sandbox", title: "Gemini CLI 跑任务并流式日志", description: "Gemini CLI + Daytona。", href: "/docs/guides/gemini/gemini-cli-run-tasks-stream-logs-sandbox" },
  { slug: "guides/google-adk/google-adk-code-generator", title: "Google ADK 代码生成器", description: "ADK 代码生成跑在沙箱。", href: "/docs/guides/google-adk/google-adk-code-generator" },
  { slug: "guides/kimi/kimi-cli-run-tasks-stream-logs-sandbox", title: "Kimi CLI 跑任务并流式日志", description: "Kimi CLI + Daytona。", href: "/docs/guides/kimi/kimi-cli-run-tasks-stream-logs-sandbox" },
  { slug: "guides/kiro/kiro-cli-run-tasks-stream-logs-sandbox", title: "Kiro CLI 跑任务并流式日志", description: "Kiro CLI + Daytona。", href: "/docs/guides/kiro/kiro-cli-run-tasks-stream-logs-sandbox" },
  { slug: "guides/langchain/langchain-data-analysis", title: "LangChain 数据分析", description: "LangChain 在沙箱里分析数据。", href: "/docs/guides/langchain/langchain-data-analysis" },
  { slug: "guides/langgraph/langgraph-plan-and-execute-data-agent", title: "LangGraph 计划-执行数据智能体", description: "LangGraph agent + Daytona。", href: "/docs/guides/langgraph/langgraph-plan-and-execute-data-agent" },
  { slug: "guides/letta-code/letta-code-agent", title: "Letta Code 智能体", description: "Letta Code 跑在沙箱。", href: "/docs/guides/letta-code/letta-code-agent" },
  { slug: "guides/mastra/mastra-coding-agent", title: "Mastra 编程智能体", description: "Mastra coding agent + Daytona。", href: "/docs/guides/mastra/mastra-coding-agent" },
  { slug: "guides/model-serving/sglang-gpu-model-serving", title: "SGLang GPU 模型服务", description: "在 GPU 沙箱上跑 SGLang。", href: "/docs/guides/model-serving/sglang-gpu-model-serving" },
  { slug: "guides/model-serving/vllm-gpu-model-serving", title: "vLLM GPU 模型服务", description: "在 GPU 沙箱上跑 vLLM。", href: "/docs/guides/model-serving/vllm-gpu-model-serving" },
  { slug: "guides/openai/codex-sdk-interactive-terminal-sandbox", title: "Codex SDK 交互终端", description: "Codex SDK 交互式沙箱。", href: "/docs/guides/openai/codex-sdk-interactive-terminal-sandbox" },
  { slug: "guides/openai/openai-agents-api-self-hosted-sandbox", title: "OpenAI Agents API 自托管沙箱", description: "Agents API 自托管到 Daytona。", href: "/docs/guides/openai/openai-agents-api-self-hosted-sandbox" },
  { slug: "guides/openai/openai-agents-sdk-with-sandboxes", title: "OpenAI Agents SDK 与沙箱", description: "Agents SDK 直接创建 Daytona 沙箱。", href: "/docs/guides/openai/openai-agents-sdk-with-sandboxes" },
  { slug: "guides/openai/text-to-sql-agent-openai-agents-sdk", title: "Text-to-SQL 智能体", description: "OpenAI Agents SDK + SQL。", href: "/docs/guides/openai/text-to-sql-agent-openai-agents-sdk" },
  { slug: "guides/openclaw/openclaw-run-secure-sandbox", title: "OpenClaw 安全沙箱", description: "把 OpenClaw 放进隔离沙箱。", href: "/docs/guides/openclaw/openclaw-run-secure-sandbox" },
  { slug: "guides/openclaw/openclaw-sdk-sandbox", title: "OpenClaw SDK 沙箱", description: "OpenClaw SDK + Daytona。", href: "/docs/guides/openclaw/openclaw-sdk-sandbox" },
  { slug: "guides/opencode/opencode-plugin", title: "OpenCode 插件", description: "OpenCode 插件对接 Daytona。", href: "/docs/guides/opencode/opencode-plugin" },
  { slug: "guides/opencode/opencode-sdk-agent", title: "OpenCode SDK 智能体", description: "OpenCode SDK agent。", href: "/docs/guides/opencode/opencode-sdk-agent" },
  { slug: "guides/opencode/opencode-web-agent", title: "OpenCode Web 智能体", description: "OpenCode Web agent。", href: "/docs/guides/opencode/opencode-web-agent" },
  { slug: "guides/pi/pi-extension", title: "Pi 扩展", description: "Pi extension 跑在 Daytona。", href: "/docs/guides/pi/pi-extension" },
  { slug: "guides/reinforcement-learning/hud-rl-cookbook", title: "HUD RL Cookbook", description: "强化学习 cookbook。", href: "/docs/guides/reinforcement-learning/hud-rl-cookbook" },
  { slug: "guides/reinforcement-learning/openenv-finqa", title: "OpenEnv FinQA", description: "金融问答 RL 环境。", href: "/docs/guides/reinforcement-learning/openenv-finqa" },
  { slug: "guides/reinforcement-learning/trl-grpo-training", title: "TRL GRPO 训练", description: "TRL GRPO 在 Daytona 上训练。", href: "/docs/guides/reinforcement-learning/trl-grpo-training" },
  { slug: "guides/reinforcement-learning/verl-retool-daytona", title: "veRL ReTool", description: "veRL ReTool + Daytona。", href: "/docs/guides/reinforcement-learning/verl-retool-daytona" },
  { slug: "guides/rlm/dspy-rlms", title: "DSPy RLM", description: "DSPy 递归语言模型。", href: "/docs/guides/rlm/dspy-rlms" },
  { slug: "guides/rlm/recursive-language-models", title: "递归语言模型", description: "RLM 在 Daytona 上的跑法。", href: "/docs/guides/rlm/recursive-language-models" },
  { slug: "guides/vercel-ai-sdk/vercel-ai-sdk-multi-language-benchmark-agent-sandbox", title: "Vercel AI SDK 多语言基准智能体", description: "Vercel AI SDK 基准沙箱。", href: "/docs/guides/vercel-ai-sdk/vercel-ai-sdk-multi-language-benchmark-agent-sandbox" },
  { slug: "go-sdk/daytona", title: "Daytona", description: "go-sdk 参考：daytona。", href: "/docs/go-sdk/daytona" },
  { slug: "go-sdk/errors", title: "Errors", description: "go-sdk 参考：errors。", href: "/docs/go-sdk/errors" },
  { slug: "go-sdk/options", title: "Options", description: "go-sdk 参考：options。", href: "/docs/go-sdk/options" },
  { slug: "go-sdk/types", title: "Types", description: "go-sdk 参考：types。", href: "/docs/go-sdk/types" },
  { slug: "java-sdk/code-interpreter", title: "Code Interpreter", description: "java-sdk 参考：code-interpreter。", href: "/docs/java-sdk/code-interpreter" },
  { slug: "java-sdk/computer-use", title: "Computer Use", description: "java-sdk 参考：computer-use。", href: "/docs/java-sdk/computer-use" },
  { slug: "java-sdk/config", title: "Config", description: "java-sdk 参考：config。", href: "/docs/java-sdk/config" },
  { slug: "java-sdk/daytona", title: "Daytona", description: "java-sdk 参考：daytona。", href: "/docs/java-sdk/daytona" },
  { slug: "java-sdk/errors", title: "Errors", description: "java-sdk 参考：errors。", href: "/docs/java-sdk/errors" },
  { slug: "java-sdk/file-system", title: "File System", description: "java-sdk 参考：file-system。", href: "/docs/java-sdk/file-system" },
  { slug: "java-sdk/git", title: "Git", description: "java-sdk 参考：git。", href: "/docs/java-sdk/git" },
  { slug: "java-sdk/image", title: "Image", description: "java-sdk 参考：image。", href: "/docs/java-sdk/image" },
  { slug: "java-sdk/lsp-server", title: "Lsp Server", description: "java-sdk 参考：lsp-server。", href: "/docs/java-sdk/lsp-server" },
  { slug: "java-sdk/process", title: "Process", description: "java-sdk 参考：process。", href: "/docs/java-sdk/process" },
  { slug: "java-sdk/pty-handle", title: "Pty Handle", description: "java-sdk 参考：pty-handle。", href: "/docs/java-sdk/pty-handle" },
  { slug: "java-sdk/pty", title: "Pty", description: "java-sdk 参考：pty。", href: "/docs/java-sdk/pty" },
  { slug: "java-sdk/sandbox", title: "Sandbox", description: "java-sdk 参考：sandbox。", href: "/docs/java-sdk/sandbox" },
  { slug: "java-sdk/secret-service", title: "Secret Service", description: "java-sdk 参考：secret-service。", href: "/docs/java-sdk/secret-service" },
  { slug: "java-sdk/snapshot", title: "Snapshot", description: "java-sdk 参考：snapshot。", href: "/docs/java-sdk/snapshot" },
  { slug: "java-sdk/volume-service", title: "Volume Service", description: "java-sdk 参考：volume-service。", href: "/docs/java-sdk/volume-service" },
  { slug: "python-sdk/async/async-code-interpreter", title: "异步 Code Interpreter", description: "python-sdk 参考：async-code-interpreter。", href: "/docs/python-sdk/async/async-code-interpreter" },
  { slug: "python-sdk/async/async-computer-use", title: "异步 Computer Use", description: "python-sdk 参考：async-computer-use。", href: "/docs/python-sdk/async/async-computer-use" },
  { slug: "python-sdk/async/async-daytona", title: "异步 Daytona", description: "python-sdk 参考：async-daytona。", href: "/docs/python-sdk/async/async-daytona" },
  { slug: "python-sdk/async/async-file-system", title: "异步 File System", description: "python-sdk 参考：async-file-system。", href: "/docs/python-sdk/async/async-file-system" },
  { slug: "python-sdk/async/async-git", title: "异步 Git", description: "python-sdk 参考：async-git。", href: "/docs/python-sdk/async/async-git" },
  { slug: "python-sdk/async/async-lsp-server", title: "异步 Lsp Server", description: "python-sdk 参考：async-lsp-server。", href: "/docs/python-sdk/async/async-lsp-server" },
  { slug: "python-sdk/async/async-object-storage", title: "异步 Object Storage", description: "python-sdk 参考：async-object-storage。", href: "/docs/python-sdk/async/async-object-storage" },
  { slug: "python-sdk/async/async-process", title: "异步 Process", description: "python-sdk 参考：async-process。", href: "/docs/python-sdk/async/async-process" },
  { slug: "python-sdk/async/async-sandbox", title: "异步 Sandbox", description: "python-sdk 参考：async-sandbox。", href: "/docs/python-sdk/async/async-sandbox" },
  { slug: "python-sdk/async/async-secret", title: "异步 Secret", description: "python-sdk 参考：async-secret。", href: "/docs/python-sdk/async/async-secret" },
  { slug: "python-sdk/async/async-snapshot", title: "异步 Snapshot", description: "python-sdk 参考：async-snapshot。", href: "/docs/python-sdk/async/async-snapshot" },
  { slug: "python-sdk/async/async-volume", title: "异步 Volume", description: "python-sdk 参考：async-volume。", href: "/docs/python-sdk/async/async-volume" },
  { slug: "python-sdk/common/charts", title: "Charts", description: "python-sdk 参考：charts。", href: "/docs/python-sdk/common/charts" },
  { slug: "python-sdk/common/errors", title: "Errors", description: "python-sdk 参考：errors。", href: "/docs/python-sdk/common/errors" },
  { slug: "python-sdk/common/image", title: "Image", description: "python-sdk 参考：image。", href: "/docs/python-sdk/common/image" },
  { slug: "python-sdk/sync/code-interpreter", title: "Code Interpreter", description: "python-sdk 参考：code-interpreter。", href: "/docs/python-sdk/sync/code-interpreter" },
  { slug: "python-sdk/sync/computer-use", title: "Computer Use", description: "python-sdk 参考：computer-use。", href: "/docs/python-sdk/sync/computer-use" },
  { slug: "python-sdk/sync/daytona", title: "Daytona", description: "python-sdk 参考：daytona。", href: "/docs/python-sdk/sync/daytona" },
  { slug: "python-sdk/sync/file-system", title: "File System", description: "python-sdk 参考：file-system。", href: "/docs/python-sdk/sync/file-system" },
  { slug: "python-sdk/sync/git", title: "Git", description: "python-sdk 参考：git。", href: "/docs/python-sdk/sync/git" },
  { slug: "python-sdk/sync/lsp-server", title: "Lsp Server", description: "python-sdk 参考：lsp-server。", href: "/docs/python-sdk/sync/lsp-server" },
  { slug: "python-sdk/sync/object-storage", title: "Object Storage", description: "python-sdk 参考：object-storage。", href: "/docs/python-sdk/sync/object-storage" },
  { slug: "python-sdk/sync/process", title: "Process", description: "python-sdk 参考：process。", href: "/docs/python-sdk/sync/process" },
  { slug: "python-sdk/sync/sandbox", title: "Sandbox", description: "python-sdk 参考：sandbox。", href: "/docs/python-sdk/sync/sandbox" },
  { slug: "python-sdk/sync/secret", title: "Secret", description: "python-sdk 参考：secret。", href: "/docs/python-sdk/sync/secret" },
  { slug: "python-sdk/sync/snapshot", title: "Snapshot", description: "python-sdk 参考：snapshot。", href: "/docs/python-sdk/sync/snapshot" },
  { slug: "python-sdk/sync/volume", title: "Volume", description: "python-sdk 参考：volume。", href: "/docs/python-sdk/sync/volume" },
  { slug: "ruby-sdk/charts", title: "Charts", description: "ruby-sdk 参考：charts。", href: "/docs/ruby-sdk/charts" },
  { slug: "ruby-sdk/computer-use", title: "Computer Use", description: "ruby-sdk 参考：computer-use。", href: "/docs/ruby-sdk/computer-use" },
  { slug: "ruby-sdk/config", title: "Config", description: "ruby-sdk 参考：config。", href: "/docs/ruby-sdk/config" },
  { slug: "ruby-sdk/daytona", title: "Daytona", description: "ruby-sdk 参考：daytona。", href: "/docs/ruby-sdk/daytona" },
  { slug: "ruby-sdk/file-system", title: "File System", description: "ruby-sdk 参考：file-system。", href: "/docs/ruby-sdk/file-system" },
  { slug: "ruby-sdk/git", title: "Git", description: "ruby-sdk 参考：git。", href: "/docs/ruby-sdk/git" },
  { slug: "ruby-sdk/image", title: "Image", description: "ruby-sdk 参考：image。", href: "/docs/ruby-sdk/image" },
  { slug: "ruby-sdk/lsp-server", title: "Lsp Server", description: "ruby-sdk 参考：lsp-server。", href: "/docs/ruby-sdk/lsp-server" },
  { slug: "ruby-sdk/object-storage", title: "Object Storage", description: "ruby-sdk 参考：object-storage。", href: "/docs/ruby-sdk/object-storage" },
  { slug: "ruby-sdk/process", title: "Process", description: "ruby-sdk 参考：process。", href: "/docs/ruby-sdk/process" },
  { slug: "ruby-sdk/sandbox", title: "Sandbox", description: "ruby-sdk 参考：sandbox。", href: "/docs/ruby-sdk/sandbox" },
  { slug: "ruby-sdk/secret-service", title: "Secret Service", description: "ruby-sdk 参考：secret-service。", href: "/docs/ruby-sdk/secret-service" },
  { slug: "ruby-sdk/secret", title: "Secret", description: "ruby-sdk 参考：secret。", href: "/docs/ruby-sdk/secret" },
  { slug: "ruby-sdk/snapshot", title: "Snapshot", description: "ruby-sdk 参考：snapshot。", href: "/docs/ruby-sdk/snapshot" },
  { slug: "ruby-sdk/volume-service", title: "Volume Service", description: "ruby-sdk 参考：volume-service。", href: "/docs/ruby-sdk/volume-service" },
  { slug: "ruby-sdk/volume", title: "Volume", description: "ruby-sdk 参考：volume。", href: "/docs/ruby-sdk/volume" },
  { slug: "typescript-sdk/charts", title: "Charts", description: "typescript-sdk 参考：charts。", href: "/docs/typescript-sdk/charts" },
  { slug: "typescript-sdk/code-interpreter", title: "Code Interpreter", description: "typescript-sdk 参考：code-interpreter。", href: "/docs/typescript-sdk/code-interpreter" },
  { slug: "typescript-sdk/computer-use", title: "Computer Use", description: "typescript-sdk 参考：computer-use。", href: "/docs/typescript-sdk/computer-use" },
  { slug: "typescript-sdk/daytona", title: "Daytona", description: "typescript-sdk 参考：daytona。", href: "/docs/typescript-sdk/daytona" },
  { slug: "typescript-sdk/errors", title: "Errors", description: "typescript-sdk 参考：errors。", href: "/docs/typescript-sdk/errors" },
  { slug: "typescript-sdk/execute-response", title: "Execute Response", description: "typescript-sdk 参考：execute-response。", href: "/docs/typescript-sdk/execute-response" },
  { slug: "typescript-sdk/file-system", title: "File System", description: "typescript-sdk 参考：file-system。", href: "/docs/typescript-sdk/file-system" },
  { slug: "typescript-sdk/git", title: "Git", description: "typescript-sdk 参考：git。", href: "/docs/typescript-sdk/git" },
  { slug: "typescript-sdk/image", title: "Image", description: "typescript-sdk 参考：image。", href: "/docs/typescript-sdk/image" },
  { slug: "typescript-sdk/lsp-server", title: "Lsp Server", description: "typescript-sdk 参考：lsp-server。", href: "/docs/typescript-sdk/lsp-server" },
  { slug: "typescript-sdk/object-storage", title: "Object Storage", description: "typescript-sdk 参考：object-storage。", href: "/docs/typescript-sdk/object-storage" },
  { slug: "typescript-sdk/process", title: "Process", description: "typescript-sdk 参考：process。", href: "/docs/typescript-sdk/process" },
  { slug: "typescript-sdk/pty-handle", title: "Pty Handle", description: "typescript-sdk 参考：pty-handle。", href: "/docs/typescript-sdk/pty-handle" },
  { slug: "typescript-sdk/pty", title: "Pty", description: "typescript-sdk 参考：pty。", href: "/docs/typescript-sdk/pty" },
  { slug: "typescript-sdk/sandbox", title: "Sandbox", description: "typescript-sdk 参考：sandbox。", href: "/docs/typescript-sdk/sandbox" },
  { slug: "typescript-sdk/secret", title: "Secret", description: "typescript-sdk 参考：secret。", href: "/docs/typescript-sdk/secret" },
  { slug: "typescript-sdk/snapshot", title: "Snapshot", description: "typescript-sdk 参考：snapshot。", href: "/docs/typescript-sdk/snapshot" },
  { slug: "typescript-sdk/volume", title: "Volume", description: "typescript-sdk 参考：volume。", href: "/docs/typescript-sdk/volume" },
  { slug: "typescript-sdk/warm-pool", title: "Warm Pool", description: "typescript-sdk 参考：warm-pool。", href: "/docs/typescript-sdk/warm-pool" },
];

function kids(prefix: string): DocLink[] {
  return PAGES.filter((p) => p.slug.startsWith(prefix) && p.slug !== prefix);
}

export const NAV: NavNode[] = [
  { kind: "label", title: "本站" },
  { kind: "link", slug: "quick-guide", title: "快速手册", href: "/docs/quick-guide" },
  { kind: "link", slug: "updates", title: "同步日志", href: "/docs/updates" },
  { kind: "link", slug: "architecture-site", title: "本站架构", href: "/docs/architecture-site" },
  { kind: "link", slug: "sitemap", title: "对照表", href: "/docs/sitemap" },
  { kind: "label", title: "开始" },
  { kind: "link", slug: "index", title: "Daytona 是什么", href: "/" },
  { kind: "link", slug: "sandboxes", title: "沙箱", href: "/docs/sandboxes" },
  { kind: "link", slug: "snapshots", title: "快照", href: "/docs/snapshots" },
  { kind: "link", slug: "volumes", title: "卷", href: "/docs/volumes" },
  { kind: "link", slug: "regions", title: "区域", href: "/docs/regions" },
  { kind: "label", title: "平台" },
  { kind: "link", slug: "architecture", title: "架构", href: "/docs/architecture" },
  { kind: "link", slug: "isolation", title: "隔离", href: "/docs/isolation" },
  { kind: "link", slug: "persistence", title: "持久化", href: "/docs/persistence" },
  { kind: "link", slug: "scale", title: "扩展", href: "/docs/scale" },
  { kind: "link", slug: "api-keys", title: "认证", href: "/docs/api-keys" },
  { kind: "link", slug: "organizations", title: "组织", href: "/docs/organizations" },
  { kind: "link", slug: "billing", title: "计费", href: "/docs/billing" },
  { kind: "link", slug: "limits", title: "限额", href: "/docs/limits" },
  { kind: "link", slug: "troubleshooting", title: "故障排查", href: "/docs/troubleshooting" },
  { kind: "link", slug: "playground", title: "Playground", href: "/docs/playground" },
  { kind: "label", title: "运行时" },
  { kind: "link", slug: "file-system-operations", title: "文件系统", href: "/docs/file-system-operations" },
  { kind: "link", slug: "git-operations", title: "Git", href: "/docs/git-operations" },
  { kind: "link", slug: "process-code-execution", title: "进程与代码", href: "/docs/process-code-execution" },
  { kind: "link", slug: "pty", title: "PTY", href: "/docs/pty" },
  { kind: "link", slug: "language-server-protocol", title: "LSP", href: "/docs/language-server-protocol" },
  { kind: "link", slug: "computer-use", title: "计算机使用", href: "/docs/computer-use" },
  { kind: "link", slug: "declarative-builder", title: "声明式构建", href: "/docs/declarative-builder" },
  { kind: "link", slug: "preview", title: "预览", href: "/docs/preview" },
  { kind: "link", slug: "web-terminal", title: "Web 终端", href: "/docs/web-terminal" },
  { kind: "link", slug: "vnc-access", title: "VNC", href: "/docs/vnc-access" },
  { kind: "link", slug: "ssh-access", title: "SSH", href: "/docs/ssh-access" },
  { kind: "link", slug: "mcp", title: "MCP", href: "/docs/mcp" },
  { kind: "link", slug: "agent-skills", title: "Agent Skills", href: "/docs/agent-skills" },
  { kind: "link", slug: "warm-pools", title: "温池", href: "/docs/warm-pools" },
  { kind: "folder", title: "更多运行时", children: [
    PAGES.find(p => p.slug === "log-streaming")!,
    PAGES.find(p => p.slug === "custom-preview-proxy")!,
    PAGES.find(p => p.slug === "mount-external-storage")!,
  ]},
  { kind: "label", title: "安全与运维" },
  { kind: "link", slug: "secrets", title: "密钥", href: "/docs/secrets" },
  { kind: "link", slug: "sso", title: "SSO", href: "/docs/sso" },
  { kind: "link", slug: "audit-logs", title: "审计日志", href: "/docs/audit-logs" },
  { kind: "link", slug: "webhooks", title: "Webhooks", href: "/docs/webhooks" },
  { kind: "link", slug: "observability/otel-collection", title: "OpenTelemetry", href: "/docs/observability/otel-collection" },
  { kind: "link", slug: "network-limits", title: "网络限额", href: "/docs/network-limits" },
  { kind: "link", slug: "vpn-connections", title: "VPN", href: "/docs/vpn-connections" },
  { kind: "link", slug: "bring-your-own-compute", title: "自带算力", href: "/docs/bring-your-own-compute" },
  { kind: "link", slug: "linked-accounts", title: "关联账号", href: "/docs/linked-accounts" },
  { kind: "label", title: "工具" },
  { kind: "link", slug: "tools/cli", title: "CLI", href: "/docs/tools/cli" },
  { kind: "link", slug: "tools/api", title: "API", href: "/docs/tools/api" },
  { kind: "link", slug: "typescript-sdk", title: "TypeScript SDK", href: "/docs/typescript-sdk" },
  { kind: "folder", title: "TypeScript 模块", children: kids("typescript-sdk") },
  { kind: "link", slug: "python-sdk", title: "Python SDK", href: "/docs/python-sdk" },
  { kind: "folder", title: "Python 模块", children: kids("python-sdk") },
  { kind: "link", slug: "go-sdk", title: "Go SDK", href: "/docs/go-sdk" },
  { kind: "folder", title: "Go 模块", children: kids("go-sdk") },
  { kind: "link", slug: "java-sdk", title: "Java SDK", href: "/docs/java-sdk" },
  { kind: "folder", title: "Java 模块", children: kids("java-sdk") },
  { kind: "link", slug: "ruby-sdk", title: "Ruby SDK", href: "/docs/ruby-sdk" },
  { kind: "folder", title: "Ruby 模块", children: kids("ruby-sdk") },
  { kind: "label", title: "指南" },
  { kind: "link", slug: "guides", title: "指南总览", href: "/docs/guides" },
  { kind: "folder", title: "Claude", children: kids("guides/claude") },
  { kind: "folder", title: "OpenAI", children: kids("guides/openai") },
  { kind: "folder", title: "Cursor / Devin / OpenCode", children: [
    ...kids("guides/cursor"), ...kids("guides/devin"), ...kids("guides/opencode"), ...kids("guides/openclaw"),
  ]},
  { kind: "folder", title: "框架与 GPU", children: [
    ...kids("guides/langchain"), ...kids("guides/langgraph"), ...kids("guides/model-serving"),
    ...kids("guides/reinforcement-learning"), ...kids("guides/rlm"), ...kids("guides/mastra"),
    ...kids("guides/google-adk"), ...kids("guides/copilotkit"), ...kids("guides/agentkit"),
    ...kids("guides/ag2"), ...kids("guides/amp"), ...kids("guides/brainbase"),
    ...kids("guides/flue"), ...kids("guides/gemini"), ...kids("guides/kimi"),
    ...kids("guides/kiro"), ...kids("guides/letta-code"), ...kids("guides/pi"),
    ...kids("guides/vercel-ai-sdk"),
  ]},
];

export function pageBySlug(slug: string): DocLink | undefined {
  const key = slug === "" || slug === "docs" ? "index" : slug.replace(/\/$/, "");
  return PAGES.find((p) => p.slug === key);
}

export function neighbors(slug: string): { prev?: DocLink; next?: DocLink } {
  const i = PAGES.findIndex((p) => p.slug === slug);
  if (i < 0) return {};
  return { prev: PAGES[i - 1], next: PAGES[i + 1] };
}

